name: built_value_generator
version: 6.3.1+move
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the dev dependency.
authors:
- David Morgan <davidmorgan@google.com>
- Clay Molocznik <clay@movemedical.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  analyzer: ^0.35.3
  analyzer_plugin: '0.0.1-alpha.7'
  build: ^1.1.3
  build_config: ^0.3.1
  built_collection: ^4.1.0
  built_value: ^6.4.0
  build_test: ^0.10.7
  source_gen: ^0.9.4+1
  quiver: '>=0.21.0 <3.0.0'

dev_dependencies:
  build_test: ^0.10.7
  build_runner: ^1.3.1
  test: ^1.5.1
  logging: ^0.11.3+2
